# Generated by Django 2.0.1 on 2019-12-25 06:07

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_content_db',
            old_name='description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='course_content_db',
            old_name='keywords',
            new_name='meta_keywords',
        ),
        migrations.RenameField(
            model_name='course_content_db',
            old_name='title',
            new_name='meta_title',
        ),
        migrations.AddField(
            model_name='course_content_db',
            name='image',
            field=models.FileField(default=datetime.datetime(2019, 12, 25, 6, 6, 36, 935444, tzinfo=utc), upload_to='course_content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_content_db',
            name='video',
            field=models.FileField(default=datetime.datetime(2019, 12, 25, 6, 6, 48, 312263, tzinfo=utc), upload_to='course_content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_content_db',
            name='details',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2019, 12, 25, 6, 7, 1, 433335, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'guest'), (1, 'teacher'), (2, 'student'), (3, 'paid')], default=0),
        ),
    ]
