# Generated by Django 2.0.1 on 2019-12-25 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0003_course_content_db_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_content_db',
            name='title',
            field=models.CharField(default=datetime.datetime(2019, 12, 25, 7, 23, 5, 365000, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
