# Generated by Django 2.0.1 on 2019-12-26 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0005_main_course_category_db_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_content_db',
            name='pdf',
            field=models.FileField(default=datetime.datetime(2019, 12, 26, 6, 33, 2, 290473, tzinfo=utc), upload_to='course_content'),
            preserve_default=False,
        ),
    ]
