# Generated by Django 2.0.1 on 2019-12-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0007_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='find',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
