# Generated by Django 2.0.1 on 2019-12-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0008_auto_20191226_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_content_db',
            name='video',
            field=models.CharField(max_length=1000),
        ),
    ]
