# Generated by Django 2.0.1 on 2019-12-27 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0009_auto_20191226_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='main_course_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ieltsapp.Main_Course_Category_Db'),
        ),
    ]
