# Generated by Django 2.0.1 on 2020-01-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0010_user_profile_main_course_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_content_db',
            name='video2',
            field=models.FileField(default='', upload_to='course_content'),
        ),
    ]
