# Generated by Django 2.0.1 on 2020-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0011_course_content_db_video2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=1000)),
                ('days', models.IntegerField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Plan_Db',
            },
        ),
    ]
