# Generated by Django 2.0.1 on 2020-01-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0012_plan_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_content_db',
            name='video',
        ),
    ]
