# Generated by Django 2.0.1 on 2020-01-22 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0013_remove_course_content_db_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_db',
            name='batch',
            field=models.ManyToManyField(blank=True, null=True, to='ieltsapp.Batch_Db'),
        ),
        migrations.AddField(
            model_name='notification_db',
            name='image',
            field=models.FileField(default=datetime.datetime(2020, 1, 22, 6, 58, 48, 176817, tzinfo=utc), upload_to='notification'),
            preserve_default=False,
        ),
    ]
