# Generated by Django 2.0.1 on 2020-01-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0014_auto_20200122_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_db',
            name='batch',
        ),
    ]
