# Generated by Django 2.0.1 on 2020-01-27 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0015_remove_notification_db_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='course_photo')),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ieltsapp.Course_Content_Db')),
            ],
        ),
        migrations.AlterField(
            model_name='plan_db',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan_db',
            name='price',
            field=models.IntegerField(),
        ),
    ]
