# Generated by Django 2.0.1 on 2020-02-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0017_auto_20200204_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_content_db',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='course_content_db',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='course_content_db',
            name='meta_title',
        ),
    ]
