# Generated by Django 2.0.1 on 2020-02-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0019_auto_20200205_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_db',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
