# Generated by Django 2.0.1 on 2020-02-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0020_auto_20200212_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_db',
            name='batch',
            field=models.ManyToManyField(blank=True, null=True, to='ieltsapp.Batch_Db'),
        ),
    ]
