# Generated by Django 2.0.1 on 2020-02-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0021_notification_db_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Notification_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Student_Notification_Db',
            },
        ),
    ]
