# Generated by Django 2.0.1 on 2020-02-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0022_student_notification_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch_db',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='blog_category_db',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course_db',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='main_course_category_db',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
