# Generated by Django 2.0.1 on 2020-02-24 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0025_auto_20200221_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_notification_db',
            name='batch',
            field=models.ManyToManyField(blank=True, null=True, to='ieltsapp.Batch_Db'),
        ),
        migrations.AddField(
            model_name='student_notification_db',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 24, 7, 14, 19, 404712, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_notification_db',
            name='details',
            field=models.CharField(default=datetime.datetime(2020, 2, 24, 7, 14, 27, 590146, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_notification_db',
            name='image',
            field=models.FileField(default=datetime.datetime(2020, 2, 24, 7, 14, 31, 703633, tzinfo=utc), upload_to='notification'),
            preserve_default=False,
        ),
    ]
