# Generated by Django 2.0.1 on 2020-02-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0026_auto_20200224_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_notification_db',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student_notification_db',
            name='date',
        ),
        migrations.RemoveField(
            model_name='student_notification_db',
            name='details',
        ),
        migrations.RemoveField(
            model_name='student_notification_db',
            name='image',
        ),
    ]
