# Generated by Django 2.0.1 on 2020-02-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0030_student_notification_db_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_notification_db',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
