# Generated by Django 2.0.1 on 2020-03-04 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0032_loggedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_content_db',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course_content_db',
            name='type',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
