# Generated by Django 2.0.1 on 2020-03-06 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0034_sub_course_category_db_sub_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_content_db',
            name='main_course_category_id',
        ),
        migrations.RemoveField(
            model_name='course_content_db',
            name='super_course_category_id',
        ),
        migrations.AlterField(
            model_name='course_content_db',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='course_content_db',
            name='sub_course_category_id',
        ),
        migrations.AddField(
            model_name='course_content_db',
            name='sub_course_category_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_course_category_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
