# Generated by Django 2.0.1 on 2020-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0035_auto_20200306_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_content_db',
            name='sub_course_category_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_course_category_id', to='ieltsapp.Sub_Course_Category_Db'),
        ),
    ]
