# Generated by Django 2.0.1 on 2020-03-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0036_auto_20200306_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_db',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ieltsapp.Main_Course_Category_Db'),
        ),
    ]
