# Generated by Django 2.0.1 on 2020-04-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0038_plan_db_main_course_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='notification')),
                ('details', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ManyToManyField(blank=True, null=True, to='ieltsapp.Batch_Db')),
            ],
            options={
                'db_table': 'Live_Db',
            },
        ),
        migrations.CreateModel(
            name='Live_Notification_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='notification')),
                ('details', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ManyToManyField(blank=True, null=True, to='ieltsapp.Batch_Db')),
            ],
            options={
                'db_table': 'Live_Notification_Db',
            },
        ),
    ]
