# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-31 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0040_auto_20200406_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_db',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
    ]
