# Generated by Django 2.0.1 on 2020-08-21 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0044_auto_20200810_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_db',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batch_db',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='students_1', to=settings.AUTH_USER_MODEL),
        ),
    ]
