# Generated by Django 2.0.1 on 2020-08-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0045_auto_20200821_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_db',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
